apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos

metadata:
  name: cpu-stress-web
  namespace: chaos-mesh

spec:
  mode: one

  selector:
    namespaces:
      - robot-shop
    labelSelectors:
      service: web

  stressors:
    cpu:
      workers: 1
      load: 80

  duration: "2m"