apiVersion: v1
kind: Service
metadata:
  name: aiops-monitor
  namespace: monitoring
  labels:
    app: aiops-monitor        # <-- ADD THIS

spec:
  selector:
    app: aiops-monitor

  ports:
    - name: http
      port: 8000
      targetPort: 8000